# Generated by scripts/generate-spytial.mjs; do not edit.
# Core 6.3.2; language 2026-09-18.
provide *
provide-types *
import lists as L

data TextSize:
  | small
  | normal
  | large
end

data LinePattern:
  | solid
  | dashed
  | dotted
end

data IconPlacement:
  | full
  | badge
end

data Direction:
  | above
  | below
  | left
  | right
  | directly-above
  | directly-below
  | directly-left
  | directly-right
end

data Hold:
  | always
  | never
end

data Rotation:
  | clockwise
  | counterclockwise
end

data Alignment:
  | horizontal
  | vertical
end

data GroupEdgeDirection:
  | no-group-edge
  | togroup
  | fromgroup
end

data LayoutFlag:
  | hide-disconnected
  | hide-disconnected-built-ins
end

data TextStyle:
  | text-style(fields :: Any)
end

data LineStyle:
  | line-style(fields :: Any)
end

data FillStyle:
  | fill-style(fields :: Any)
end

data BorderStyle:
  | border-style(fields :: Any)
end

data IconStyle:
  | icon-style(fields :: Any)
end

data RuleSource:
  | rule-source(fields :: Any)
end

data GroupAddEdge:
  | group-add-edge(fields :: Any)
end

data Constraint:
  | spytial-orientation(selector :: String, directions :: L.List<Direction>, options :: Any)
  | spytial-cyclic(selector :: String, options :: Any)
  | spytial-align(selector :: String, direction :: Alignment, options :: Any)
  | spytial-group(selector :: String, name :: String, options :: Any)
  | spytial-size(width :: Number, height :: Number, options :: Any)
  | spytial-hide-atom(selector :: String, options :: Any)
end

data Directive:
  | spytial-flag(name :: LayoutFlag)
  | spytial-atom-style(selector :: String, options :: Any)
  | spytial-edge-style(field :: String, options :: Any)
  | spytial-attribute(field :: String, options :: Any)
  | spytial-tag(to-tag :: String, name :: String, value :: String, options :: Any)
  | spytial-hide-field(field :: String, options :: Any)
  | spytial-inferred-edge(name :: String, selector :: String, options :: Any)
  | spytial-icon(selector :: String, path :: String, options :: Any)
  | spytial-atom-color(value :: String, selector :: String, options :: Any)
  | spytial-edge-color(field :: String, value :: String, options :: Any)
end

data SpytialRule:
  | constraint(value :: Constraint)
  | directive(value :: Directive)
end

fun orientation(selector :: String, directions :: L.List<Direction>) -> SpytialRule:
  constraint(spytial-orientation(selector, directions, {}))
end
fun orientation-with(selector :: String, directions :: L.List<Direction>, options :: Any) -> SpytialRule:
  constraint(spytial-orientation(selector, directions, options))
end

fun cyclic(selector :: String) -> SpytialRule:
  constraint(spytial-cyclic(selector, {}))
end
fun cyclic-with(selector :: String, options :: Any) -> SpytialRule:
  constraint(spytial-cyclic(selector, options))
end

fun align(selector :: String, direction :: Alignment) -> SpytialRule:
  constraint(spytial-align(selector, direction, {}))
end
fun align-with(selector :: String, direction :: Alignment, options :: Any) -> SpytialRule:
  constraint(spytial-align(selector, direction, options))
end

fun group(selector :: String, name :: String) -> SpytialRule:
  constraint(spytial-group(selector, name, {}))
end
fun group-with(selector :: String, name :: String, options :: Any) -> SpytialRule:
  constraint(spytial-group(selector, name, options))
end

fun size(width :: Number, height :: Number) -> SpytialRule:
  constraint(spytial-size(width, height, {}))
end
fun size-with(width :: Number, height :: Number, options :: Any) -> SpytialRule:
  constraint(spytial-size(width, height, options))
end

fun hide-atom(selector :: String) -> SpytialRule:
  constraint(spytial-hide-atom(selector, {}))
end
fun hide-atom-with(selector :: String, options :: Any) -> SpytialRule:
  constraint(spytial-hide-atom(selector, options))
end

fun flag(name :: LayoutFlag) -> SpytialRule:
  directive(spytial-flag(name))
end

fun atom-style(selector :: String, style :: Any) -> SpytialRule:
  directive(spytial-atom-style(selector, style))
end

fun edge-style(field :: String, style :: Any) -> SpytialRule:
  directive(spytial-edge-style(field, style))
end

fun attribute(field :: String) -> SpytialRule:
  directive(spytial-attribute(field, {}))
end
fun attribute-with(field :: String, options :: Any) -> SpytialRule:
  directive(spytial-attribute(field, options))
end

fun tag(to-tag :: String, name :: String, value :: String) -> SpytialRule:
  directive(spytial-tag(to-tag, name, value, {}))
end
fun tag-with(to-tag :: String, name :: String, value :: String, options :: Any) -> SpytialRule:
  directive(spytial-tag(to-tag, name, value, options))
end

fun hide-field(field :: String) -> SpytialRule:
  directive(spytial-hide-field(field, {}))
end
fun hide-field-with(field :: String, options :: Any) -> SpytialRule:
  directive(spytial-hide-field(field, options))
end

fun inferred-edge(name :: String, selector :: String) -> SpytialRule:
  directive(spytial-inferred-edge(name, selector, {}))
end
fun inferred-edge-with(name :: String, selector :: String, options :: Any) -> SpytialRule:
  directive(spytial-inferred-edge(name, selector, options))
end

fun icon(selector :: String, path :: String) -> SpytialRule:
  directive(spytial-icon(selector, path, {}))
end
fun icon-with(selector :: String, path :: String, options :: Any) -> SpytialRule:
  directive(spytial-icon(selector, path, options))
end

fun atom-color(value :: String, selector :: String) -> SpytialRule:
  directive(spytial-atom-color(value, selector, {}))
end
fun atom-color-with(value :: String, selector :: String, options :: Any) -> SpytialRule:
  directive(spytial-atom-color(value, selector, options))
end

fun edge-color(field :: String, value :: String) -> SpytialRule:
  directive(spytial-edge-color(field, value, {}))
end
fun edge-color-with(field :: String, value :: String, options :: Any) -> SpytialRule:
  directive(spytial-edge-color(field, value, options))
end
