# Generated by scripts/generate-spytial.mjs; do not edit.
# Core 6.3.1; language 2026-09-18.
provide *
provide-types *

data TextSize:
  | text-size-small
  | text-size-normal
  | text-size-large
end

data LinePattern:
  | line-pattern-solid
  | line-pattern-dashed
  | line-pattern-dotted
end

data IconPlacement:
  | icon-placement-full
  | icon-placement-badge
end

data Direction:
  | direction-above
  | direction-below
  | direction-left
  | direction-right
  | direction-directly-above
  | direction-directly-below
  | direction-directly-left
  | direction-directly-right
end

data Hold:
  | hold-always
  | hold-never
end

data Rotation:
  | rotation-clockwise
  | rotation-counterclockwise
end

data Alignment:
  | alignment-horizontal
  | alignment-vertical
end

data GroupEdgeDirection:
  | group-edge-direction-none
  | group-edge-direction-togroup
  | group-edge-direction-fromgroup
end

data LayoutFlag:
  | layout-flag-hide-disconnected
  | layout-flag-hide-disconnected-built-ins
end

data TextStyle:
  | text-style(size :: Option<TextSize>, color :: Option<String>) with:
    method with-size(self, new-value :: TextSize) -> TextStyle:
      text-style(some(new-value), self.color)
    end,
    method with-color(self, new-value :: String) -> TextStyle:
      text-style(self.size, some(new-value))
    end
end
default-text-style = text-style(none, none)

data LineStyle:
  | line-style(color :: Option<String>, pattern :: Option<LinePattern>, weight :: Option<Number>, highlight :: Option<String>) with:
    method with-color(self, new-value :: String) -> LineStyle:
      line-style(some(new-value), self.pattern, self.weight, self.highlight)
    end,
    method with-pattern(self, new-value :: LinePattern) -> LineStyle:
      line-style(self.color, some(new-value), self.weight, self.highlight)
    end,
    method with-weight(self, new-value :: Number) -> LineStyle:
      line-style(self.color, self.pattern, some(new-value), self.highlight)
    end,
    method with-highlight(self, new-value :: String) -> LineStyle:
      line-style(self.color, self.pattern, self.weight, some(new-value))
    end
end
default-line-style = line-style(none, none, none, none)

data FillStyle:
  | fill-style(color :: Option<String>) with:
    method with-color(self, new-value :: String) -> FillStyle:
      fill-style(some(new-value))
    end
end
default-fill-style = fill-style(none)

data BorderStyle:
  | border-style(color :: Option<String>, width :: Option<Number>) with:
    method with-color(self, new-value :: String) -> BorderStyle:
      border-style(some(new-value), self.width)
    end,
    method with-width(self, new-value :: Number) -> BorderStyle:
      border-style(self.color, some(new-value))
    end
end
default-border-style = border-style(none, none)

data IconStyle:
  | icon-style(path :: Option<String>, placement :: Option<IconPlacement>, opacity :: Option<Number>) with:
    method with-path(self, new-value :: String) -> IconStyle:
      icon-style(some(new-value), self.placement, self.opacity)
    end,
    method with-placement(self, new-value :: IconPlacement) -> IconStyle:
      icon-style(self.path, some(new-value), self.opacity)
    end,
    method with-opacity(self, new-value :: Number) -> IconStyle:
      icon-style(self.path, self.placement, some(new-value))
    end
end
default-icon-style = icon-style(none, none, none)

data RuleSource:
  | rule-source(text :: String, location :: Option<String>) with:
    method with-text(self, new-value :: String) -> RuleSource:
      rule-source(new-value, self.location)
    end,
    method with-location(self, new-value :: String) -> RuleSource:
      rule-source(self.text, some(new-value))
    end
end

data GroupAddEdge:
  | group-add-edge(points :: Option<GroupEdgeDirection>, line-style :: Option<LineStyle>, text-style :: Option<TextStyle>) with:
    method with-points(self, new-value :: GroupEdgeDirection) -> GroupAddEdge:
      group-add-edge(some(new-value), self.line-style, self.text-style)
    end,
    method with-line-style(self, new-value :: LineStyle) -> GroupAddEdge:
      group-add-edge(self.points, some(new-value), self.text-style)
    end,
    method with-text-style(self, new-value :: TextStyle) -> GroupAddEdge:
      group-add-edge(self.points, self.line-style, some(new-value))
    end
end
default-group-add-edge = group-add-edge(none, none, none)

data OrientationOptions:
  | orientation-options(hold :: Option<Hold>, source :: Option<RuleSource>) with:
    method with-hold(self, new-value :: Hold) -> OrientationOptions:
      orientation-options(some(new-value), self.source)
    end,
    method with-source(self, new-value :: RuleSource) -> OrientationOptions:
      orientation-options(self.hold, some(new-value))
    end
end
default-orientation-options = orientation-options(none, none)

data CyclicOptions:
  | cyclic-options(direction :: Option<Rotation>, hold :: Option<Hold>, source :: Option<RuleSource>) with:
    method with-direction(self, new-value :: Rotation) -> CyclicOptions:
      cyclic-options(some(new-value), self.hold, self.source)
    end,
    method with-hold(self, new-value :: Hold) -> CyclicOptions:
      cyclic-options(self.direction, some(new-value), self.source)
    end,
    method with-source(self, new-value :: RuleSource) -> CyclicOptions:
      cyclic-options(self.direction, self.hold, some(new-value))
    end
end
default-cyclic-options = cyclic-options(none, none, none)

data AlignOptions:
  | align-options(hold :: Option<Hold>, source :: Option<RuleSource>) with:
    method with-hold(self, new-value :: Hold) -> AlignOptions:
      align-options(some(new-value), self.source)
    end,
    method with-source(self, new-value :: RuleSource) -> AlignOptions:
      align-options(self.hold, some(new-value))
    end
end
default-align-options = align-options(none, none)

data GroupOptions:
  | group-options(add-edge :: Option<GroupAddEdge>, show-label :: Option<Boolean>, text-style :: Option<TextStyle>, hold :: Option<Hold>, source :: Option<RuleSource>) with:
    method with-add-edge(self, new-value :: GroupAddEdge) -> GroupOptions:
      group-options(some(new-value), self.show-label, self.text-style, self.hold, self.source)
    end,
    method with-show-label(self, new-value :: Boolean) -> GroupOptions:
      group-options(self.add-edge, some(new-value), self.text-style, self.hold, self.source)
    end,
    method with-text-style(self, new-value :: TextStyle) -> GroupOptions:
      group-options(self.add-edge, self.show-label, some(new-value), self.hold, self.source)
    end,
    method with-hold(self, new-value :: Hold) -> GroupOptions:
      group-options(self.add-edge, self.show-label, self.text-style, some(new-value), self.source)
    end,
    method with-source(self, new-value :: RuleSource) -> GroupOptions:
      group-options(self.add-edge, self.show-label, self.text-style, self.hold, some(new-value))
    end
end
default-group-options = group-options(none, none, none, none, none)

data SizeOptions:
  | size-options(selector :: Option<String>, source :: Option<RuleSource>) with:
    method with-selector(self, new-value :: String) -> SizeOptions:
      size-options(some(new-value), self.source)
    end,
    method with-source(self, new-value :: RuleSource) -> SizeOptions:
      size-options(self.selector, some(new-value))
    end
end
default-size-options = size-options(none, none)

data HideAtomOptions:
  | hide-atom-options(source :: Option<RuleSource>) with:
    method with-source(self, new-value :: RuleSource) -> HideAtomOptions:
      hide-atom-options(some(new-value))
    end
end
default-hide-atom-options = hide-atom-options(none)

data AtomStyleOptions:
  | atom-style-options(selector :: Option<String>, fill-style :: Option<FillStyle>, border-style :: Option<BorderStyle>, icon-style :: Option<IconStyle>, text-style :: Option<TextStyle>, show-label :: Option<Boolean>, source :: Option<RuleSource>) with:
    method with-selector(self, new-value :: String) -> AtomStyleOptions:
      atom-style-options(some(new-value), self.fill-style, self.border-style, self.icon-style, self.text-style, self.show-label, self.source)
    end,
    method with-fill-style(self, new-value :: FillStyle) -> AtomStyleOptions:
      atom-style-options(self.selector, some(new-value), self.border-style, self.icon-style, self.text-style, self.show-label, self.source)
    end,
    method with-border-style(self, new-value :: BorderStyle) -> AtomStyleOptions:
      atom-style-options(self.selector, self.fill-style, some(new-value), self.icon-style, self.text-style, self.show-label, self.source)
    end,
    method with-icon-style(self, new-value :: IconStyle) -> AtomStyleOptions:
      atom-style-options(self.selector, self.fill-style, self.border-style, some(new-value), self.text-style, self.show-label, self.source)
    end,
    method with-text-style(self, new-value :: TextStyle) -> AtomStyleOptions:
      atom-style-options(self.selector, self.fill-style, self.border-style, self.icon-style, some(new-value), self.show-label, self.source)
    end,
    method with-show-label(self, new-value :: Boolean) -> AtomStyleOptions:
      atom-style-options(self.selector, self.fill-style, self.border-style, self.icon-style, self.text-style, some(new-value), self.source)
    end,
    method with-source(self, new-value :: RuleSource) -> AtomStyleOptions:
      atom-style-options(self.selector, self.fill-style, self.border-style, self.icon-style, self.text-style, self.show-label, some(new-value))
    end
end
default-atom-style-options = atom-style-options(none, none, none, none, none, none, none)

data EdgeStyleOptions:
  | edge-style-options(selector :: Option<String>, filter :: Option<String>, line-style :: Option<LineStyle>, text-style :: Option<TextStyle>, show-label :: Option<Boolean>, hidden :: Option<Boolean>, source :: Option<RuleSource>) with:
    method with-selector(self, new-value :: String) -> EdgeStyleOptions:
      edge-style-options(some(new-value), self.filter, self.line-style, self.text-style, self.show-label, self.hidden, self.source)
    end,
    method with-filter(self, new-value :: String) -> EdgeStyleOptions:
      edge-style-options(self.selector, some(new-value), self.line-style, self.text-style, self.show-label, self.hidden, self.source)
    end,
    method with-line-style(self, new-value :: LineStyle) -> EdgeStyleOptions:
      edge-style-options(self.selector, self.filter, some(new-value), self.text-style, self.show-label, self.hidden, self.source)
    end,
    method with-text-style(self, new-value :: TextStyle) -> EdgeStyleOptions:
      edge-style-options(self.selector, self.filter, self.line-style, some(new-value), self.show-label, self.hidden, self.source)
    end,
    method with-show-label(self, new-value :: Boolean) -> EdgeStyleOptions:
      edge-style-options(self.selector, self.filter, self.line-style, self.text-style, some(new-value), self.hidden, self.source)
    end,
    method with-hidden(self, new-value :: Boolean) -> EdgeStyleOptions:
      edge-style-options(self.selector, self.filter, self.line-style, self.text-style, self.show-label, some(new-value), self.source)
    end,
    method with-source(self, new-value :: RuleSource) -> EdgeStyleOptions:
      edge-style-options(self.selector, self.filter, self.line-style, self.text-style, self.show-label, self.hidden, some(new-value))
    end
end
default-edge-style-options = edge-style-options(none, none, none, none, none, none, none)

data AttributeOptions:
  | attribute-options(selector :: Option<String>, filter :: Option<String>, text-style :: Option<TextStyle>, source :: Option<RuleSource>) with:
    method with-selector(self, new-value :: String) -> AttributeOptions:
      attribute-options(some(new-value), self.filter, self.text-style, self.source)
    end,
    method with-filter(self, new-value :: String) -> AttributeOptions:
      attribute-options(self.selector, some(new-value), self.text-style, self.source)
    end,
    method with-text-style(self, new-value :: TextStyle) -> AttributeOptions:
      attribute-options(self.selector, self.filter, some(new-value), self.source)
    end,
    method with-source(self, new-value :: RuleSource) -> AttributeOptions:
      attribute-options(self.selector, self.filter, self.text-style, some(new-value))
    end
end
default-attribute-options = attribute-options(none, none, none, none)

data TagOptions:
  | tag-options(text-style :: Option<TextStyle>, source :: Option<RuleSource>) with:
    method with-text-style(self, new-value :: TextStyle) -> TagOptions:
      tag-options(some(new-value), self.source)
    end,
    method with-source(self, new-value :: RuleSource) -> TagOptions:
      tag-options(self.text-style, some(new-value))
    end
end
default-tag-options = tag-options(none, none)

data HideFieldOptions:
  | hide-field-options(selector :: Option<String>, filter :: Option<String>, source :: Option<RuleSource>) with:
    method with-selector(self, new-value :: String) -> HideFieldOptions:
      hide-field-options(some(new-value), self.filter, self.source)
    end,
    method with-filter(self, new-value :: String) -> HideFieldOptions:
      hide-field-options(self.selector, some(new-value), self.source)
    end,
    method with-source(self, new-value :: RuleSource) -> HideFieldOptions:
      hide-field-options(self.selector, self.filter, some(new-value))
    end
end
default-hide-field-options = hide-field-options(none, none, none)

data InferredEdgeOptions:
  | inferred-edge-options(draw :: Option<String>, line-style :: Option<LineStyle>, text-style :: Option<TextStyle>, color :: Option<String>, style :: Option<LinePattern>, weight :: Option<Number>, highlight :: Option<String>, source :: Option<RuleSource>) with:
    method with-draw(self, new-value :: String) -> InferredEdgeOptions:
      inferred-edge-options(some(new-value), self.line-style, self.text-style, self.color, self.style, self.weight, self.highlight, self.source)
    end,
    method with-line-style(self, new-value :: LineStyle) -> InferredEdgeOptions:
      inferred-edge-options(self.draw, some(new-value), self.text-style, self.color, self.style, self.weight, self.highlight, self.source)
    end,
    method with-text-style(self, new-value :: TextStyle) -> InferredEdgeOptions:
      inferred-edge-options(self.draw, self.line-style, some(new-value), self.color, self.style, self.weight, self.highlight, self.source)
    end,
    method with-color(self, new-value :: String) -> InferredEdgeOptions:
      inferred-edge-options(self.draw, self.line-style, self.text-style, some(new-value), self.style, self.weight, self.highlight, self.source)
    end,
    method with-style(self, new-value :: LinePattern) -> InferredEdgeOptions:
      inferred-edge-options(self.draw, self.line-style, self.text-style, self.color, some(new-value), self.weight, self.highlight, self.source)
    end,
    method with-weight(self, new-value :: Number) -> InferredEdgeOptions:
      inferred-edge-options(self.draw, self.line-style, self.text-style, self.color, self.style, some(new-value), self.highlight, self.source)
    end,
    method with-highlight(self, new-value :: String) -> InferredEdgeOptions:
      inferred-edge-options(self.draw, self.line-style, self.text-style, self.color, self.style, self.weight, some(new-value), self.source)
    end,
    method with-source(self, new-value :: RuleSource) -> InferredEdgeOptions:
      inferred-edge-options(self.draw, self.line-style, self.text-style, self.color, self.style, self.weight, self.highlight, some(new-value))
    end
end
default-inferred-edge-options = inferred-edge-options(none, none, none, none, none, none, none, none)

data IconOptions:
  | icon-options(show-labels :: Option<Boolean>, source :: Option<RuleSource>) with:
    method with-show-labels(self, new-value :: Boolean) -> IconOptions:
      icon-options(some(new-value), self.source)
    end,
    method with-source(self, new-value :: RuleSource) -> IconOptions:
      icon-options(self.show-labels, some(new-value))
    end
end
default-icon-options = icon-options(none, none)

data AtomColorOptions:
  | atom-color-options(source :: Option<RuleSource>) with:
    method with-source(self, new-value :: RuleSource) -> AtomColorOptions:
      atom-color-options(some(new-value))
    end
end
default-atom-color-options = atom-color-options(none)

data EdgeColorOptions:
  | edge-color-options(selector :: Option<String>, filter :: Option<String>, style :: Option<LinePattern>, weight :: Option<Number>, highlight :: Option<String>, show-label :: Option<Boolean>, hidden :: Option<Boolean>, source :: Option<RuleSource>) with:
    method with-selector(self, new-value :: String) -> EdgeColorOptions:
      edge-color-options(some(new-value), self.filter, self.style, self.weight, self.highlight, self.show-label, self.hidden, self.source)
    end,
    method with-filter(self, new-value :: String) -> EdgeColorOptions:
      edge-color-options(self.selector, some(new-value), self.style, self.weight, self.highlight, self.show-label, self.hidden, self.source)
    end,
    method with-style(self, new-value :: LinePattern) -> EdgeColorOptions:
      edge-color-options(self.selector, self.filter, some(new-value), self.weight, self.highlight, self.show-label, self.hidden, self.source)
    end,
    method with-weight(self, new-value :: Number) -> EdgeColorOptions:
      edge-color-options(self.selector, self.filter, self.style, some(new-value), self.highlight, self.show-label, self.hidden, self.source)
    end,
    method with-highlight(self, new-value :: String) -> EdgeColorOptions:
      edge-color-options(self.selector, self.filter, self.style, self.weight, some(new-value), self.show-label, self.hidden, self.source)
    end,
    method with-show-label(self, new-value :: Boolean) -> EdgeColorOptions:
      edge-color-options(self.selector, self.filter, self.style, self.weight, self.highlight, some(new-value), self.hidden, self.source)
    end,
    method with-hidden(self, new-value :: Boolean) -> EdgeColorOptions:
      edge-color-options(self.selector, self.filter, self.style, self.weight, self.highlight, self.show-label, some(new-value), self.source)
    end,
    method with-source(self, new-value :: RuleSource) -> EdgeColorOptions:
      edge-color-options(self.selector, self.filter, self.style, self.weight, self.highlight, self.show-label, self.hidden, some(new-value))
    end
end
default-edge-color-options = edge-color-options(none, none, none, none, none, none, none, none)

data Constraint:
  | spytial-orientation(selector :: String, directions :: List<Direction>, options :: OrientationOptions)
  | spytial-cyclic(selector :: String, options :: CyclicOptions)
  | spytial-align(selector :: String, direction :: Alignment, options :: AlignOptions)
  | spytial-group(selector :: String, name :: String, options :: GroupOptions)
  | spytial-size(width :: Number, height :: Number, options :: SizeOptions)
  | spytial-hide-atom(selector :: String, options :: HideAtomOptions)
end

data Directive:
  | spytial-flag(name :: LayoutFlag)
  | spytial-atom-style(options :: AtomStyleOptions)
  | spytial-edge-style(field :: String, options :: EdgeStyleOptions)
  | spytial-attribute(field :: String, options :: AttributeOptions)
  | spytial-tag(to-tag :: String, name :: String, value :: String, options :: TagOptions)
  | spytial-hide-field(field :: String, options :: HideFieldOptions)
  | spytial-inferred-edge(name :: String, selector :: String, options :: InferredEdgeOptions)
  | spytial-icon(selector :: String, path :: String, options :: IconOptions)
  | spytial-atom-color(value :: String, selector :: String, options :: AtomColorOptions)
  | spytial-edge-color(field :: String, value :: String, options :: EdgeColorOptions)
end

data SpytialRule:
  | constraint(value :: Constraint)
  | directive(value :: Directive)
end

fun orientation(selector :: String, directions :: List<Direction>) -> SpytialRule:
  constraint(spytial-orientation(selector, directions, default-orientation-options))
end
fun orientation-with(selector :: String, directions :: List<Direction>, options :: OrientationOptions) -> SpytialRule:
  constraint(spytial-orientation(selector, directions, options))
end

fun cyclic(selector :: String) -> SpytialRule:
  constraint(spytial-cyclic(selector, default-cyclic-options))
end
fun cyclic-with(selector :: String, options :: CyclicOptions) -> SpytialRule:
  constraint(spytial-cyclic(selector, options))
end

fun align(selector :: String, direction :: Alignment) -> SpytialRule:
  constraint(spytial-align(selector, direction, default-align-options))
end
fun align-with(selector :: String, direction :: Alignment, options :: AlignOptions) -> SpytialRule:
  constraint(spytial-align(selector, direction, options))
end

fun group(selector :: String, name :: String) -> SpytialRule:
  constraint(spytial-group(selector, name, default-group-options))
end
fun group-with(selector :: String, name :: String, options :: GroupOptions) -> SpytialRule:
  constraint(spytial-group(selector, name, options))
end

fun size(width :: Number, height :: Number) -> SpytialRule:
  constraint(spytial-size(width, height, default-size-options))
end
fun size-with(width :: Number, height :: Number, options :: SizeOptions) -> SpytialRule:
  constraint(spytial-size(width, height, options))
end

fun hide-atom(selector :: String) -> SpytialRule:
  constraint(spytial-hide-atom(selector, default-hide-atom-options))
end
fun hide-atom-with(selector :: String, options :: HideAtomOptions) -> SpytialRule:
  constraint(spytial-hide-atom(selector, options))
end

fun flag(name :: LayoutFlag) -> SpytialRule:
  directive(spytial-flag(name))
end

fun atom-style() -> SpytialRule:
  directive(spytial-atom-style(default-atom-style-options))
end
fun atom-style-with(options :: AtomStyleOptions) -> SpytialRule:
  directive(spytial-atom-style(options))
end

fun edge-style(field :: String) -> SpytialRule:
  directive(spytial-edge-style(field, default-edge-style-options))
end
fun edge-style-with(field :: String, options :: EdgeStyleOptions) -> SpytialRule:
  directive(spytial-edge-style(field, options))
end

fun attribute(field :: String) -> SpytialRule:
  directive(spytial-attribute(field, default-attribute-options))
end
fun attribute-with(field :: String, options :: AttributeOptions) -> SpytialRule:
  directive(spytial-attribute(field, options))
end

fun tag(to-tag :: String, name :: String, value :: String) -> SpytialRule:
  directive(spytial-tag(to-tag, name, value, default-tag-options))
end
fun tag-with(to-tag :: String, name :: String, value :: String, options :: TagOptions) -> SpytialRule:
  directive(spytial-tag(to-tag, name, value, options))
end

fun hide-field(field :: String) -> SpytialRule:
  directive(spytial-hide-field(field, default-hide-field-options))
end
fun hide-field-with(field :: String, options :: HideFieldOptions) -> SpytialRule:
  directive(spytial-hide-field(field, options))
end

fun inferred-edge(name :: String, selector :: String) -> SpytialRule:
  directive(spytial-inferred-edge(name, selector, default-inferred-edge-options))
end
fun inferred-edge-with(name :: String, selector :: String, options :: InferredEdgeOptions) -> SpytialRule:
  directive(spytial-inferred-edge(name, selector, options))
end

fun icon(selector :: String, path :: String) -> SpytialRule:
  directive(spytial-icon(selector, path, default-icon-options))
end
fun icon-with(selector :: String, path :: String, options :: IconOptions) -> SpytialRule:
  directive(spytial-icon(selector, path, options))
end

fun atom-color(value :: String, selector :: String) -> SpytialRule:
  directive(spytial-atom-color(value, selector, default-atom-color-options))
end
fun atom-color-with(value :: String, selector :: String, options :: AtomColorOptions) -> SpytialRule:
  directive(spytial-atom-color(value, selector, options))
end

fun edge-color(field :: String, value :: String) -> SpytialRule:
  directive(spytial-edge-color(field, value, default-edge-color-options))
end
fun edge-color-with(field :: String, value :: String, options :: EdgeColorOptions) -> SpytialRule:
  directive(spytial-edge-color(field, value, options))
end
