// Generated by scripts/generate-spytial.mjs; do not edit.
export const spytialSchema = {
  "languageVersion": "2026-09-18",
  "coreVersion": "6.3.2",
  "enums": {
    "TextSize": {
      "text-size-small": "small",
      "text-size-normal": "normal",
      "text-size-large": "large"
    },
    "LinePattern": {
      "line-pattern-solid": "solid",
      "line-pattern-dashed": "dashed",
      "line-pattern-dotted": "dotted"
    },
    "IconPlacement": {
      "icon-placement-full": "full",
      "icon-placement-badge": "badge"
    },
    "Direction": {
      "direction-above": "above",
      "direction-below": "below",
      "direction-left": "left",
      "direction-right": "right",
      "direction-directly-above": "directlyAbove",
      "direction-directly-below": "directlyBelow",
      "direction-directly-left": "directlyLeft",
      "direction-directly-right": "directlyRight"
    },
    "Hold": {
      "hold-always": "always",
      "hold-never": "never"
    },
    "Rotation": {
      "rotation-clockwise": "clockwise",
      "rotation-counterclockwise": "counterclockwise"
    },
    "Alignment": {
      "alignment-horizontal": "horizontal",
      "alignment-vertical": "vertical"
    },
    "GroupEdgeDirection": {
      "group-edge-direction-none": "none",
      "group-edge-direction-togroup": "togroup",
      "group-edge-direction-fromgroup": "fromgroup"
    },
    "LayoutFlag": {
      "layout-flag-hide-disconnected": "hideDisconnected",
      "layout-flag-hide-disconnected-built-ins": "hideDisconnectedBuiltIns"
    }
  },
  "blocks": {
    "textStyle": {
      "name": "textStyle",
      "typeName": "TextStyle",
      "constructor": "text-style",
      "fields": [
        {
          "name": "size",
          "pyretName": "size",
          "type": "enum",
          "required": false,
          "enum": "TextSize"
        },
        {
          "name": "color",
          "pyretName": "color",
          "type": "color",
          "required": false
        }
      ]
    },
    "lineStyle": {
      "name": "lineStyle",
      "typeName": "LineStyle",
      "constructor": "line-style",
      "fields": [
        {
          "name": "color",
          "pyretName": "color",
          "type": "color",
          "required": false
        },
        {
          "name": "pattern",
          "pyretName": "pattern",
          "type": "enum",
          "required": false,
          "enum": "LinePattern"
        },
        {
          "name": "weight",
          "pyretName": "weight",
          "type": "number",
          "required": false,
          "exclusiveMinimum": 0
        },
        {
          "name": "highlight",
          "pyretName": "highlight",
          "type": "color",
          "required": false
        }
      ]
    },
    "fillStyle": {
      "name": "fillStyle",
      "typeName": "FillStyle",
      "constructor": "fill-style",
      "fields": [
        {
          "name": "color",
          "pyretName": "color",
          "type": "color",
          "required": false
        }
      ]
    },
    "borderStyle": {
      "name": "borderStyle",
      "typeName": "BorderStyle",
      "constructor": "border-style",
      "fields": [
        {
          "name": "color",
          "pyretName": "color",
          "type": "color",
          "required": false
        },
        {
          "name": "width",
          "pyretName": "width",
          "type": "number",
          "required": false,
          "exclusiveMinimum": 0
        }
      ]
    },
    "iconStyle": {
      "name": "iconStyle",
      "typeName": "IconStyle",
      "constructor": "icon-style",
      "fields": [
        {
          "name": "path",
          "pyretName": "path",
          "type": "icon-path",
          "required": false
        },
        {
          "name": "placement",
          "pyretName": "placement",
          "type": "enum",
          "required": false,
          "enum": "IconPlacement"
        },
        {
          "name": "opacity",
          "pyretName": "opacity",
          "type": "number",
          "required": false,
          "minimum": 0,
          "maximum": 1
        }
      ]
    },
    "ruleSource": {
      "name": "ruleSource",
      "typeName": "RuleSource",
      "constructor": "rule-source",
      "fields": [
        {
          "name": "text",
          "pyretName": "text",
          "type": "string",
          "required": true
        },
        {
          "name": "location",
          "pyretName": "location",
          "type": "string",
          "required": false
        }
      ]
    },
    "groupAddEdge": {
      "name": "groupAddEdge",
      "typeName": "GroupAddEdge",
      "constructor": "group-add-edge",
      "fields": [
        {
          "name": "points",
          "pyretName": "points",
          "type": "enum",
          "required": false,
          "enum": "GroupEdgeDirection"
        },
        {
          "name": "lineStyle",
          "pyretName": "line-style",
          "type": "block",
          "required": false,
          "block": "lineStyle"
        },
        {
          "name": "textStyle",
          "pyretName": "text-style",
          "type": "block",
          "required": false,
          "block": "textStyle"
        }
      ]
    }
  },
  "rules": {
    "orientation": {
      "name": "orientation",
      "yamlKey": "orientation",
      "section": "constraints",
      "shape": "mapping",
      "constructor": "spytial-orientation",
      "optionsConstructor": "orientation-options",
      "fields": [
        {
          "name": "selector",
          "pyretName": "selector",
          "type": "selector",
          "required": true
        },
        {
          "name": "directions",
          "pyretName": "directions",
          "type": "enum-list",
          "required": true,
          "listRules": {
            "atMostOneOf": [
              [
                "above",
                "below"
              ],
              [
                "left",
                "right"
              ]
            ],
            "narrowsListTo": {
              "directlyAbove": [
                "above",
                "directlyAbove"
              ],
              "directlyBelow": [
                "below",
                "directlyBelow"
              ],
              "directlyLeft": [
                "left",
                "directlyLeft"
              ],
              "directlyRight": [
                "right",
                "directlyRight"
              ]
            }
          },
          "enum": "Direction"
        },
        {
          "name": "hold",
          "pyretName": "hold",
          "type": "enum",
          "required": false,
          "enum": "Hold"
        },
        {
          "name": "source",
          "pyretName": "source",
          "type": "block",
          "required": false,
          "block": "ruleSource"
        }
      ]
    },
    "cyclic": {
      "name": "cyclic",
      "yamlKey": "cyclic",
      "section": "constraints",
      "shape": "mapping",
      "constructor": "spytial-cyclic",
      "optionsConstructor": "cyclic-options",
      "fields": [
        {
          "name": "selector",
          "pyretName": "selector",
          "type": "selector",
          "required": true
        },
        {
          "name": "direction",
          "pyretName": "direction",
          "type": "enum",
          "required": false,
          "enum": "Rotation"
        },
        {
          "name": "hold",
          "pyretName": "hold",
          "type": "enum",
          "required": false,
          "enum": "Hold"
        },
        {
          "name": "source",
          "pyretName": "source",
          "type": "block",
          "required": false,
          "block": "ruleSource"
        }
      ]
    },
    "align": {
      "name": "align",
      "yamlKey": "align",
      "section": "constraints",
      "shape": "mapping",
      "constructor": "spytial-align",
      "optionsConstructor": "align-options",
      "fields": [
        {
          "name": "selector",
          "pyretName": "selector",
          "type": "selector",
          "required": true
        },
        {
          "name": "direction",
          "pyretName": "direction",
          "type": "enum",
          "required": true,
          "enum": "Alignment"
        },
        {
          "name": "hold",
          "pyretName": "hold",
          "type": "enum",
          "required": false,
          "enum": "Hold"
        },
        {
          "name": "source",
          "pyretName": "source",
          "type": "block",
          "required": false,
          "block": "ruleSource"
        }
      ]
    },
    "group": {
      "name": "group",
      "yamlKey": "group",
      "section": "constraints",
      "shape": "mapping",
      "constructor": "spytial-group",
      "optionsConstructor": "group-options",
      "fields": [
        {
          "name": "selector",
          "pyretName": "selector",
          "type": "selector",
          "required": true
        },
        {
          "name": "name",
          "pyretName": "name",
          "type": "string",
          "required": true
        },
        {
          "name": "addEdge",
          "pyretName": "add-edge",
          "type": "block",
          "required": false,
          "block": "groupAddEdge"
        },
        {
          "name": "showLabel",
          "pyretName": "show-label",
          "type": "boolean",
          "required": false
        },
        {
          "name": "textStyle",
          "pyretName": "text-style",
          "type": "block",
          "required": false,
          "block": "textStyle"
        },
        {
          "name": "hold",
          "pyretName": "hold",
          "type": "enum",
          "required": false,
          "enum": "Hold"
        },
        {
          "name": "source",
          "pyretName": "source",
          "type": "block",
          "required": false,
          "block": "ruleSource"
        }
      ]
    },
    "size": {
      "name": "size",
      "yamlKey": "size",
      "section": "constraints",
      "shape": "mapping",
      "constructor": "spytial-size",
      "optionsConstructor": "size-options",
      "fields": [
        {
          "name": "width",
          "pyretName": "width",
          "type": "number",
          "required": true,
          "exclusiveMinimum": 0
        },
        {
          "name": "height",
          "pyretName": "height",
          "type": "number",
          "required": true,
          "exclusiveMinimum": 0
        },
        {
          "name": "selector",
          "pyretName": "selector",
          "type": "selector",
          "required": false
        },
        {
          "name": "source",
          "pyretName": "source",
          "type": "block",
          "required": false,
          "block": "ruleSource"
        }
      ]
    },
    "hideAtom": {
      "name": "hideAtom",
      "yamlKey": "hideAtom",
      "section": "constraints",
      "shape": "mapping",
      "constructor": "spytial-hide-atom",
      "optionsConstructor": "hide-atom-options",
      "fields": [
        {
          "name": "selector",
          "pyretName": "selector",
          "type": "selector",
          "required": true
        },
        {
          "name": "source",
          "pyretName": "source",
          "type": "block",
          "required": false,
          "block": "ruleSource"
        }
      ]
    },
    "flag": {
      "name": "flag",
      "yamlKey": "flag",
      "section": "directives",
      "shape": "scalar",
      "constructor": "spytial-flag",
      "optionsConstructor": "flag-options",
      "fields": [
        {
          "name": "flag",
          "pyretName": "name",
          "type": "enum",
          "required": true,
          "enum": "LayoutFlag"
        }
      ]
    },
    "atomStyle": {
      "name": "atomStyle",
      "yamlKey": "atomStyle",
      "section": "directives",
      "shape": "mapping",
      "constructor": "spytial-atom-style",
      "optionsConstructor": "atom-style-options",
      "fields": [
        {
          "name": "selector",
          "pyretName": "selector",
          "type": "selector",
          "required": false
        },
        {
          "name": "fillStyle",
          "pyretName": "fill-style",
          "type": "block",
          "required": false,
          "block": "fillStyle"
        },
        {
          "name": "borderStyle",
          "pyretName": "border-style",
          "type": "block",
          "required": false,
          "block": "borderStyle"
        },
        {
          "name": "iconStyle",
          "pyretName": "icon-style",
          "type": "block",
          "required": false,
          "block": "iconStyle"
        },
        {
          "name": "textStyle",
          "pyretName": "text-style",
          "type": "block",
          "required": false,
          "block": "textStyle"
        },
        {
          "name": "showLabel",
          "pyretName": "show-label",
          "type": "boolean",
          "required": false
        },
        {
          "name": "source",
          "pyretName": "source",
          "type": "block",
          "required": false,
          "block": "ruleSource"
        }
      ]
    },
    "edgeStyle": {
      "name": "edgeStyle",
      "yamlKey": "edgeStyle",
      "section": "directives",
      "shape": "mapping",
      "constructor": "spytial-edge-style",
      "optionsConstructor": "edge-style-options",
      "fields": [
        {
          "name": "field",
          "pyretName": "field",
          "type": "relation",
          "required": true
        },
        {
          "name": "selector",
          "pyretName": "selector",
          "type": "selector",
          "required": false
        },
        {
          "name": "filter",
          "pyretName": "filter",
          "type": "selector",
          "required": false
        },
        {
          "name": "lineStyle",
          "pyretName": "line-style",
          "type": "block",
          "required": false,
          "block": "lineStyle"
        },
        {
          "name": "textStyle",
          "pyretName": "text-style",
          "type": "block",
          "required": false,
          "block": "textStyle"
        },
        {
          "name": "showLabel",
          "pyretName": "show-label",
          "type": "boolean",
          "required": false
        },
        {
          "name": "hidden",
          "pyretName": "hidden",
          "type": "boolean",
          "required": false
        },
        {
          "name": "source",
          "pyretName": "source",
          "type": "block",
          "required": false,
          "block": "ruleSource"
        }
      ]
    },
    "attribute": {
      "name": "attribute",
      "yamlKey": "attribute",
      "section": "directives",
      "shape": "mapping",
      "constructor": "spytial-attribute",
      "optionsConstructor": "attribute-options",
      "fields": [
        {
          "name": "field",
          "pyretName": "field",
          "type": "relation",
          "required": true
        },
        {
          "name": "selector",
          "pyretName": "selector",
          "type": "selector",
          "required": false
        },
        {
          "name": "filter",
          "pyretName": "filter",
          "type": "selector",
          "required": false
        },
        {
          "name": "textStyle",
          "pyretName": "text-style",
          "type": "block",
          "required": false,
          "block": "textStyle"
        },
        {
          "name": "source",
          "pyretName": "source",
          "type": "block",
          "required": false,
          "block": "ruleSource"
        }
      ]
    },
    "tag": {
      "name": "tag",
      "yamlKey": "tag",
      "section": "directives",
      "shape": "mapping",
      "constructor": "spytial-tag",
      "optionsConstructor": "tag-options",
      "fields": [
        {
          "name": "toTag",
          "pyretName": "to-tag",
          "type": "selector",
          "required": true
        },
        {
          "name": "name",
          "pyretName": "name",
          "type": "string",
          "required": true
        },
        {
          "name": "value",
          "pyretName": "value",
          "type": "selector",
          "required": true
        },
        {
          "name": "textStyle",
          "pyretName": "text-style",
          "type": "block",
          "required": false,
          "block": "textStyle"
        },
        {
          "name": "source",
          "pyretName": "source",
          "type": "block",
          "required": false,
          "block": "ruleSource"
        }
      ]
    },
    "hideField": {
      "name": "hideField",
      "yamlKey": "hideField",
      "section": "directives",
      "shape": "mapping",
      "constructor": "spytial-hide-field",
      "optionsConstructor": "hide-field-options",
      "fields": [
        {
          "name": "field",
          "pyretName": "field",
          "type": "relation",
          "required": true
        },
        {
          "name": "selector",
          "pyretName": "selector",
          "type": "selector",
          "required": false
        },
        {
          "name": "filter",
          "pyretName": "filter",
          "type": "selector",
          "required": false
        },
        {
          "name": "source",
          "pyretName": "source",
          "type": "block",
          "required": false,
          "block": "ruleSource"
        }
      ]
    },
    "inferredEdge": {
      "name": "inferredEdge",
      "yamlKey": "inferredEdge",
      "section": "directives",
      "shape": "mapping",
      "constructor": "spytial-inferred-edge",
      "optionsConstructor": "inferred-edge-options",
      "fields": [
        {
          "name": "name",
          "pyretName": "name",
          "type": "string",
          "required": true
        },
        {
          "name": "selector",
          "pyretName": "selector",
          "type": "selector",
          "required": true
        },
        {
          "name": "draw",
          "pyretName": "draw",
          "type": "string",
          "required": false,
          "pattern": "^\\s*[^\\s](?:(?!->)[\\s\\S])*->(?:(?!->)[\\s\\S])*[^\\s]\\s*$"
        },
        {
          "name": "lineStyle",
          "pyretName": "line-style",
          "type": "block",
          "required": false,
          "block": "lineStyle"
        },
        {
          "name": "textStyle",
          "pyretName": "text-style",
          "type": "block",
          "required": false,
          "block": "textStyle"
        },
        {
          "name": "color",
          "pyretName": "color",
          "type": "color",
          "required": false
        },
        {
          "name": "style",
          "pyretName": "style",
          "type": "enum",
          "required": false,
          "enum": "LinePattern"
        },
        {
          "name": "weight",
          "pyretName": "weight",
          "type": "number",
          "required": false,
          "exclusiveMinimum": 0
        },
        {
          "name": "highlight",
          "pyretName": "highlight",
          "type": "color",
          "required": false
        },
        {
          "name": "source",
          "pyretName": "source",
          "type": "block",
          "required": false,
          "block": "ruleSource"
        }
      ]
    },
    "icon": {
      "name": "icon",
      "yamlKey": "icon",
      "section": "directives",
      "shape": "mapping",
      "constructor": "spytial-icon",
      "optionsConstructor": "icon-options",
      "fields": [
        {
          "name": "selector",
          "pyretName": "selector",
          "type": "selector",
          "required": true
        },
        {
          "name": "path",
          "pyretName": "path",
          "type": "icon-path",
          "required": true
        },
        {
          "name": "showLabels",
          "pyretName": "show-labels",
          "type": "boolean",
          "required": false
        },
        {
          "name": "source",
          "pyretName": "source",
          "type": "block",
          "required": false,
          "block": "ruleSource"
        }
      ]
    },
    "atomColor": {
      "name": "atomColor",
      "yamlKey": "atomColor",
      "section": "directives",
      "shape": "mapping",
      "constructor": "spytial-atom-color",
      "optionsConstructor": "atom-color-options",
      "fields": [
        {
          "name": "value",
          "pyretName": "value",
          "type": "color",
          "required": true
        },
        {
          "name": "selector",
          "pyretName": "selector",
          "type": "selector",
          "required": true
        },
        {
          "name": "source",
          "pyretName": "source",
          "type": "block",
          "required": false,
          "block": "ruleSource"
        }
      ]
    },
    "edgeColor": {
      "name": "edgeColor",
      "yamlKey": "edgeColor",
      "section": "directives",
      "shape": "mapping",
      "constructor": "spytial-edge-color",
      "optionsConstructor": "edge-color-options",
      "fields": [
        {
          "name": "field",
          "pyretName": "field",
          "type": "relation",
          "required": true
        },
        {
          "name": "value",
          "pyretName": "value",
          "type": "color",
          "required": true
        },
        {
          "name": "selector",
          "pyretName": "selector",
          "type": "selector",
          "required": false
        },
        {
          "name": "filter",
          "pyretName": "filter",
          "type": "selector",
          "required": false
        },
        {
          "name": "style",
          "pyretName": "style",
          "type": "enum",
          "required": false,
          "enum": "LinePattern"
        },
        {
          "name": "weight",
          "pyretName": "weight",
          "type": "number",
          "required": false,
          "exclusiveMinimum": 0
        },
        {
          "name": "highlight",
          "pyretName": "highlight",
          "type": "color",
          "required": false
        },
        {
          "name": "showLabel",
          "pyretName": "show-label",
          "type": "boolean",
          "required": false
        },
        {
          "name": "hidden",
          "pyretName": "hidden",
          "type": "boolean",
          "required": false
        },
        {
          "name": "source",
          "pyretName": "source",
          "type": "block",
          "required": false,
          "block": "ruleSource"
        }
      ]
    }
  }
} as const;
